version: '3'

tasks:
  clean:
    aliases: [c]
    cmds:
      - make clean

  build:
    alises: [b]
    cmds:
      - make all

  edit:
    aliases: [e]
    cmds:
      - nvim fpga_driver.c

  install:
    aliases: [i]
    cmds:
      - task: build
      - cmd: sudo rmmod fpga_driver
        ignore_error: true
      - cmd: sudo insmod fpga_driver.ko
