version: '3'

tasks:
  clean:
    aliases: [c]
    cmds:
      - cmd: mv compile_commands.json ..
        ignore_error: true
      - cmd: make clean
      - cmd: mv ../compile_commands.json .
        ignore_error: true

  build:
    aliases: [b]
    cmds:
      - make all -j

  edit:
    aliases: [e]
    cmds:
      - nvim fpga_driver.c

  install:
    aliases: [i]
    cmds:
      - task: build
      - cmd: sudo rmmod fpga_driver
        ignore_error: true
      - cmd: sudo insmod fpga_driver.ko
