version: '3'

tasks:
  init:
    aliases: [i]
    cmds:
      - rm -rf build
      - mkdir -p build
      - cd build && cmake -DCMAKE_BUILD_TYPE=Release ..

  build:
    aliases: [b]
    dir: build 
    cmds: 
      - cmake --build . -j

  test:
    aliases: [t]
    cmds:
      - task: build
      - echo "1" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo
      - sudo ./build/MatrixAcceleratorDemo
