version: '3'

tasks:
  build:
    aliases: [b]
    cmds: 
      - g++ demo.cpp -o demo #-O3

  test:
    aliases: [t]
    cmds:
      - task: build
      - echo "1" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo
      - sudo ./demo #; sudo dmesg | tail -n 5
